// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYVoi5-nX0lm6wSk-vtin5eGLgy0OZ4fA',
    appId: '1:1046526949508:web:eea85688335dcbfe1aaad1',
    messagingSenderId: '1046526949508',
    projectId: 'swift-guess',
    authDomain: 'swift-guess.firebaseapp.com',
    storageBucket: 'swift-guess.firebasestorage.app',
    measurementId: 'G-W7Q6J3W1H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlFNJ7BjNbOebYaOWc9jo9MEf8r17ZaKs',
    appId: '1:1046526949508:android:f7ff2dfcc27c54a01aaad1',
    messagingSenderId: '1046526949508',
    projectId: 'swift-guess',
    storageBucket: 'swift-guess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqAiSpvN7i94Umautv4CYkKwoc-gXwhGQ',
    appId: '1:1046526949508:ios:fd1718ea5ee8e0ff1aaad1',
    messagingSenderId: '1046526949508',
    projectId: 'swift-guess',
    storageBucket: 'swift-guess.firebasestorage.app',
    iosBundleId: 'com.example.swiftGuess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqAiSpvN7i94Umautv4CYkKwoc-gXwhGQ',
    appId: '1:1046526949508:ios:fd1718ea5ee8e0ff1aaad1',
    messagingSenderId: '1046526949508',
    projectId: 'swift-guess',
    storageBucket: 'swift-guess.firebasestorage.app',
    iosBundleId: 'com.example.swiftGuess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYVoi5-nX0lm6wSk-vtin5eGLgy0OZ4fA',
    appId: '1:1046526949508:web:e70377c424316c991aaad1',
    messagingSenderId: '1046526949508',
    projectId: 'swift-guess',
    authDomain: 'swift-guess.firebaseapp.com',
    storageBucket: 'swift-guess.firebasestorage.app',
    measurementId: 'G-4GWV70B1G7',
  );
}
